name: black

on:
  push:
      branches:
        - develop
        - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./wnutils"
          version: "~= 26.0"
